language: python
sudo: required

cache:
  directories:
    - $HOME/.cache/pip

matrix:
    include:
        - os: linux
          python: "2.6"
        - os: linux
          python: "2.7"
        - os: linux
          python: "3.2"
        - os: linux
          python: "3.3"
        - os: linux
          python: "3.4"
        - os: linux
          python: "3.5"
        - os: linux
          python: "nightly" # currently points to 3.6-dev
        - os: osx
          language: generic
          env: TOXENV=py27
        - os: osx
          language: generic
          env: TOXENV=py35

# command to install dependencies
install:
   - ./.travis/install.sh
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python setup.py install; fi
   # no sudo for osx, so use --user
   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py install --user; fi

# command to run tests
script:
  - python unittests.py

