language: python
sudo: required

cache:
  directories:
    - $HOME/.cache/pip

matrix:
    include:
        - os: linux
          python:
             - "2.6"
             - "2.7"
             - "3.2"
             - "3.3"
             - "3.4"
             - "3.5"
             - "nightly" # currently points to 3.6-dev
        - os: osx
          language: generic
          env:
             - TOXENV=py27
             - TOXENV=py35

# command to install dependencies
install:
   - ./.travis/install.sh
   - python setup.py install

# command to run tests
script:
  - python unittests.py

