language: python

cache:
  directories:
    - $HOME/.cache/pip

os:
  - linux
  - osx

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

before_install:
# adding an echo seems not to work ...
# - echo "before_install os:" "$TRAVIS_OS_NAME"
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
   - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y gfortran; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated gcc || brew upgrade gcc; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install python3; fi

# command to install dependencies
install:
  - pip install numpy
  - python setup.py install

# command to run tests
# script: nosetests
script:
  - python unittests.py

